function ret = P_0(t)
%P_0 simulate the function laser generated by the laser emmiter
%By Zhuziliwww 2022/11/22
%   t: time in ns
%   ret: the signal intensity got in t ns
    
    %Initialization of the parameters
    M = 1; % modulation depth 
    TAU_0 = 0; % laser half width in ns
    TAU = 3; % laser impulse width in ns
    P_0 = 1000000; % Amplitude of the generated impulse
    F_M = 225*(10^6); % modulation frequency in Hz
    
    ret = P_0*((1+M*cos(2*pi*F_M*(t-TAU_0)))*exp(-(t-TAU_0)^2/(TAU^2)));
end

