function ret = P_0(t,F_M,TAU, TAU_0)
%P_0 simulate the function laser generated by the laser emmiter
%By Zhuziliwww 2022/11/22
%   t: time in ns
%   ret: the signal intensity got in t ns
    arguments
        t = 0;
        F_M = 225*(10^6); % modulation frequency in Hz
        TAU = 30; % laser impulse width in ns
        TAU_0 = 0; % laser half width in ns
    end
    %Initialization of the parameters
    M = 1; % modulation depth 
    P_0 = 1000; % Amplitude of the generated impulse
    ret = P_0*((1+M*cos(2*pi*F_M*(t-TAU_0)*(10^-9)))*exp(-(t-TAU_0)^2/(TAU^2)));
end

